gcc-env:
  compiler:
  - toolchain: gcc
  spec: gcc@11
  unify: true
  specs:
  - cuda@11.8
  - intel-mkl^cray-mpich
  # CP2K
  - cosma@master +scalapack +cuda
  - libint@2.6.0 +fortran tune=cp2k-lmax-6
  - libxc@6.1.0 #~shared +cuda
  - spglib@1.16.1
  - libxsmm@1.17 +shared
  - dbcsr@2.5.0 smm=libxsmm +cuda cuda_arch=80
  - fftw@3.3.10 +mpi +openmp # TODO: Fix CP2K CMake to use FFT via MKL or CUDA 
  # DLAF
  - blaspp ^intel-mkl
  - lapackpp ^intel-mkl
  - mimalloc
  - fmt
  - camp
  - umpire@5.0.1 +cuda ~shared ~examples
  - pika +mpi +cuda
  - pika-algorithms
  - whip +cuda
  - googletest
  mpi:
   spec: cray-mpich
   gpu: cuda
tools:
  compiler:
  - toolchain: gcc
    spec: gcc@11
  unify: true
  specs:
  - cmake@3.25.2
  - pkgconfig
  - git
  - python@3.9
  - doxygen
